
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BpmDataService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://127.0.0.1:4546/BPMService/BpmDataService/?wsdl")
public class BpmDataService
    extends Service
{

    private final static URL BPMDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException BPMDATASERVICE_EXCEPTION;
    private final static QName BPMDATASERVICE_QNAME = new QName("http://tempuri.org/", "BpmDataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:4546/BPMService/BpmDataService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPMDATASERVICE_WSDL_LOCATION = url;
        BPMDATASERVICE_EXCEPTION = e;
    }

    public BpmDataService() {
        super(__getWsdlLocation(), BPMDATASERVICE_QNAME);
    }

    public BpmDataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPMDATASERVICE_QNAME, features);
    }

    public BpmDataService(URL wsdlLocation) {
        super(wsdlLocation, BPMDATASERVICE_QNAME);
    }

    public BpmDataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPMDATASERVICE_QNAME, features);
    }

    public BpmDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpmDataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBPMWebInterface
     */
    @WebEndpoint(name = "BasicHttpBinding_IBPMWebInterface")
    public IBPMWebInterface getBasicHttpBindingIBPMWebInterface() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IBPMWebInterface"), IBPMWebInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBPMWebInterface
     */
    @WebEndpoint(name = "BasicHttpBinding_IBPMWebInterface")
    public IBPMWebInterface getBasicHttpBindingIBPMWebInterface(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IBPMWebInterface"), IBPMWebInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPMDATASERVICE_EXCEPTION!= null) {
            throw BPMDATASERVICE_EXCEPTION;
        }
        return BPMDATASERVICE_WSDL_LOCATION;
    }

}
