
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfanyType;
import org.datacontract.schemas._2004._07.bpmdevices.BatteryPackThreshold;
import org.datacontract.schemas._2004._07.bpmdevices.BatteryThreshold;
import org.datacontract.schemas._2004._07.bpmdevices_vendor.AlarmAlarmType;
import org.datacontract.schemas._2004._07.bpmdevices_vendor.ArrayOfAlarm;
import org.datacontract.schemas._2004._07.bpmdevices_vendor.ArrayOfBattery;
import org.datacontract.schemas._2004._07.bpmdevices_vendor.ArrayOfBatteryPack;
import org.datacontract.schemas._2004._07.bpmdevices_vendor.ArrayOfCircuitInfo;
import org.datacontract.schemas._2004._07.bpmdevices_vendor.Battery;
import org.datacontract.schemas._2004._07.bpmdevices_vendor.BatteryPack;
import org.datacontract.schemas._2004._07.bpmdevices_vendor.CircuitInfo;
import org.datacontract.schemas._2004._07.bpmdevices_vendor.SfBCU;
import org.datacontract.schemas._2004._07.bpmdevices_vendor.SfECU;
import org.datacontract.schemas._2004._07.bpmservice.BatteryPackInfo;
import org.datacontract.schemas._2004._07.bpmservice.CurentDucer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBPMWebInterface", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    org.datacontract.schemas._2004._07.bpmdevices.ObjectFactory.class,
    org.datacontract.schemas._2004._07.bpmdevices_vendor.ObjectFactory.class,
    org.datacontract.schemas._2004._07.bpmservice.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IBPMWebInterface {


    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmdevices_vendor.ArrayOfCircuitInfo
     */
    @WebMethod(operationName = "GetCircuitInfoList", action = "http://tempuri.org/IBPMWebInterface/GetCircuitInfoList")
    @WebResult(name = "GetCircuitInfoListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCircuitInfoList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCircuitInfoList")
    @ResponseWrapper(localName = "GetCircuitInfoListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCircuitInfoListResponse")
    public ArrayOfCircuitInfo getCircuitInfoList();

    /**
     * 
     * @param areaId
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmdevices_vendor.ArrayOfCircuitInfo
     */
    @WebMethod(operationName = "GetCircuits", action = "http://tempuri.org/IBPMWebInterface/GetCircuits")
    @WebResult(name = "GetCircuitsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCircuits", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCircuits")
    @ResponseWrapper(localName = "GetCircuitsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCircuitsResponse")
    public ArrayOfCircuitInfo getCircuits(
        @WebParam(name = "areaId", targetNamespace = "http://tempuri.org/")
        Long areaId);

    /**
     * 
     * @param area
     * @param batteriesVisible
     * @param pageIndex
     * @param pageDataCount
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmdevices_vendor.ArrayOfCircuitInfo
     */
    @WebMethod(operationName = "GetCircuitInfos", action = "http://tempuri.org/IBPMWebInterface/GetCircuitInfos")
    @WebResult(name = "GetCircuitInfosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCircuitInfos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCircuitInfos")
    @ResponseWrapper(localName = "GetCircuitInfosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCircuitInfosResponse")
    public ArrayOfCircuitInfo getCircuitInfos(
        @WebParam(name = "area", targetNamespace = "http://tempuri.org/")
        Long area,
        @WebParam(name = "pageIndex", targetNamespace = "http://tempuri.org/")
        Integer pageIndex,
        @WebParam(name = "pageDataCount", targetNamespace = "http://tempuri.org/")
        Integer pageDataCount,
        @WebParam(name = "batteriesVisible", targetNamespace = "http://tempuri.org/")
        Boolean batteriesVisible);

    /**
     * 
     * @param area
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "GetCircuitsCount", action = "http://tempuri.org/IBPMWebInterface/GetCircuitsCount")
    @WebResult(name = "GetCircuitsCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCircuitsCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCircuitsCount")
    @ResponseWrapper(localName = "GetCircuitsCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCircuitsCountResponse")
    public Long getCircuitsCount(
        @WebParam(name = "area", targetNamespace = "http://tempuri.org/")
        Long area);

    /**
     * 
     * @param batteryPackId
     * @param areaId
     * @param batteryId
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmdevices_vendor.ArrayOfCircuitInfo
     */
    @WebMethod(operationName = "GetCircuitList", action = "http://tempuri.org/IBPMWebInterface/GetCircuitList")
    @WebResult(name = "GetCircuitListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCircuitList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCircuitList")
    @ResponseWrapper(localName = "GetCircuitListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCircuitListResponse")
    public ArrayOfCircuitInfo getCircuitList(
        @WebParam(name = "areaId", targetNamespace = "http://tempuri.org/")
        Long areaId,
        @WebParam(name = "batteryPackId", targetNamespace = "http://tempuri.org/")
        Long batteryPackId,
        @WebParam(name = "batteryId", targetNamespace = "http://tempuri.org/")
        Long batteryId);

    /**
     * 
     * @param createUserId
     * @param circuitInfo
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddCircuit", action = "http://tempuri.org/IBPMWebInterface/AddCircuit")
    @WebResult(name = "AddCircuitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddCircuit", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddCircuit")
    @ResponseWrapper(localName = "AddCircuitResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddCircuitResponse")
    public Boolean addCircuit(
        @WebParam(name = "circuitInfo", targetNamespace = "http://tempuri.org/")
        CircuitInfo circuitInfo,
        @WebParam(name = "createUserId", targetNamespace = "http://tempuri.org/")
        Long createUserId);

    /**
     * 
     * @param id
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmdevices_vendor.CircuitInfo
     */
    @WebMethod(operationName = "GetCircuit", action = "http://tempuri.org/IBPMWebInterface/GetCircuit")
    @WebResult(name = "GetCircuitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCircuit", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCircuit")
    @ResponseWrapper(localName = "GetCircuitResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCircuitResponse")
    public CircuitInfo getCircuit(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Long id);

    /**
     * 
     * @param id
     * @param userId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveCircuit", action = "http://tempuri.org/IBPMWebInterface/RemoveCircuit")
    @WebResult(name = "RemoveCircuitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RemoveCircuit", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveCircuit")
    @ResponseWrapper(localName = "RemoveCircuitResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveCircuitResponse")
    public Boolean removeCircuit(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Long id,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        Long userId);

    /**
     * 
     * @param updateUserId
     * @param circuitInfo
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateCircuit", action = "http://tempuri.org/IBPMWebInterface/UpdateCircuit")
    @WebResult(name = "UpdateCircuitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateCircuit", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateCircuit")
    @ResponseWrapper(localName = "UpdateCircuitResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateCircuitResponse")
    public Boolean updateCircuit(
        @WebParam(name = "circuitInfo", targetNamespace = "http://tempuri.org/")
        CircuitInfo circuitInfo,
        @WebParam(name = "updateUserId", targetNamespace = "http://tempuri.org/")
        Long updateUserId);

    /**
     * 
     * @param id
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmservice.BatteryPackInfo
     */
    @WebMethod(operationName = "GetBatteryPack", action = "http://tempuri.org/IBPMWebInterface/GetBatteryPack")
    @WebResult(name = "GetBatteryPackResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBatteryPack", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryPack")
    @ResponseWrapper(localName = "GetBatteryPackResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryPackResponse")
    public BatteryPackInfo getBatteryPack(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Long id);

    /**
     * 
     * @param batteryPack
     * @param userId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddBatteryPack", action = "http://tempuri.org/IBPMWebInterface/AddBatteryPack")
    @WebResult(name = "AddBatteryPackResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddBatteryPack", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddBatteryPack")
    @ResponseWrapper(localName = "AddBatteryPackResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddBatteryPackResponse")
    public Boolean addBatteryPack(
        @WebParam(name = "batteryPack", targetNamespace = "http://tempuri.org/")
        BatteryPack batteryPack,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        Long userId);

    /**
     * 
     * @param batteryPack
     * @param userId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateBatteryPack", action = "http://tempuri.org/IBPMWebInterface/UpdateBatteryPack")
    @WebResult(name = "UpdateBatteryPackResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateBatteryPack", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateBatteryPack")
    @ResponseWrapper(localName = "UpdateBatteryPackResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateBatteryPackResponse")
    public Boolean updateBatteryPack(
        @WebParam(name = "batteryPack", targetNamespace = "http://tempuri.org/")
        BatteryPack batteryPack,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        Long userId);

    /**
     * 
     * @param batteryPackId
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetCircuitBatteryPack", action = "http://tempuri.org/IBPMWebInterface/SetCircuitBatteryPack")
    @WebResult(name = "SetCircuitBatteryPackResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetCircuitBatteryPack", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetCircuitBatteryPack")
    @ResponseWrapper(localName = "SetCircuitBatteryPackResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetCircuitBatteryPackResponse")
    public Boolean setCircuitBatteryPack(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "batteryPackId", targetNamespace = "http://tempuri.org/")
        Long batteryPackId);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveCircuitBatteryPack", action = "http://tempuri.org/IBPMWebInterface/RemoveCircuitBatteryPack")
    @WebResult(name = "RemoveCircuitBatteryPackResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RemoveCircuitBatteryPack", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveCircuitBatteryPack")
    @ResponseWrapper(localName = "RemoveCircuitBatteryPackResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveCircuitBatteryPackResponse")
    public Boolean removeCircuitBatteryPack(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Long id);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveBatteryPack", action = "http://tempuri.org/IBPMWebInterface/RemoveBatteryPack")
    @WebResult(name = "RemoveBatteryPackResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RemoveBatteryPack", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveBatteryPack")
    @ResponseWrapper(localName = "RemoveBatteryPackResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveBatteryPackResponse")
    public Boolean removeBatteryPack(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Long id);

    /**
     * 
     * @param batteryPackId
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmdevices_vendor.ArrayOfBattery
     */
    @WebMethod(operationName = "GetBatteries", action = "http://tempuri.org/IBPMWebInterface/GetBatteries")
    @WebResult(name = "GetBatteriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBatteries", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteries")
    @ResponseWrapper(localName = "GetBatteriesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteriesResponse")
    public ArrayOfBattery getBatteries(
        @WebParam(name = "batteryPackId", targetNamespace = "http://tempuri.org/")
        Long batteryPackId);

    /**
     * 
     * @param batteryPackId
     * @param index
     * @param battery
     * @param userId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddBattery", action = "http://tempuri.org/IBPMWebInterface/AddBattery")
    @WebResult(name = "AddBatteryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddBattery", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddBattery")
    @ResponseWrapper(localName = "AddBatteryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddBatteryResponse")
    public Boolean addBattery(
        @WebParam(name = "battery", targetNamespace = "http://tempuri.org/")
        Battery battery,
        @WebParam(name = "index", targetNamespace = "http://tempuri.org/")
        Integer index,
        @WebParam(name = "batteryPackId", targetNamespace = "http://tempuri.org/")
        Long batteryPackId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        Long userId);

    /**
     * 
     * @param batteryId
     * @param userId
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveBattery", action = "http://tempuri.org/IBPMWebInterface/RemoveBattery")
    @WebResult(name = "RemoveBatteryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RemoveBattery", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveBattery")
    @ResponseWrapper(localName = "RemoveBatteryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveBatteryResponse")
    public Boolean removeBattery(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "batteryId", targetNamespace = "http://tempuri.org/")
        Long batteryId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        Long userId);

    /**
     * 
     * @param batteryId
     * @param userId
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RecoveryBattery", action = "http://tempuri.org/IBPMWebInterface/RecoveryBattery")
    @WebResult(name = "RecoveryBatteryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RecoveryBattery", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RecoveryBattery")
    @ResponseWrapper(localName = "RecoveryBatteryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RecoveryBatteryResponse")
    public Boolean recoveryBattery(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "batteryId", targetNamespace = "http://tempuri.org/")
        Long batteryId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        Long userId);

    /**
     * 
     * @param batteryId
     * @param userId
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DisableBattery", action = "http://tempuri.org/IBPMWebInterface/DisableBattery")
    @WebResult(name = "DisableBatteryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DisableBattery", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DisableBattery")
    @ResponseWrapper(localName = "DisableBatteryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DisableBatteryResponse")
    public Boolean disableBattery(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "batteryId", targetNamespace = "http://tempuri.org/")
        Long batteryId,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        Long userId);

    /**
     * 
     * @param name
     * @param category
     * @param type
     * @param config
     * @param userId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddDevice", action = "http://tempuri.org/IBPMWebInterface/AddDevice")
    @WebResult(name = "AddDeviceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddDevice", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddDevice")
    @ResponseWrapper(localName = "AddDeviceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddDeviceResponse")
    public Boolean addDevice(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "category", targetNamespace = "http://tempuri.org/")
        Integer category,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "config", targetNamespace = "http://tempuri.org/")
        String config,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        Long userId);

    /**
     * 
     * @param category
     * @param deviceId
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "CircuitAddDevice", action = "http://tempuri.org/IBPMWebInterface/CircuitAddDevice")
    @WebResult(name = "CircuitAddDeviceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CircuitAddDevice", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CircuitAddDevice")
    @ResponseWrapper(localName = "CircuitAddDeviceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CircuitAddDeviceResponse")
    public Boolean circuitAddDevice(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "category", targetNamespace = "http://tempuri.org/")
        Byte category,
        @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
        Long deviceId);

    /**
     * 
     * @param id
     * @param config
     * @param userId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateDevice", action = "http://tempuri.org/IBPMWebInterface/UpdateDevice")
    @WebResult(name = "UpdateDeviceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateDevice", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateDevice")
    @ResponseWrapper(localName = "UpdateDeviceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateDeviceResponse")
    public Boolean updateDevice(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Long id,
        @WebParam(name = "config", targetNamespace = "http://tempuri.org/")
        String config,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        Long userId);

    /**
     * 
     * @param id
     * @param userId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveDevice", action = "http://tempuri.org/IBPMWebInterface/RemoveDevice")
    @WebResult(name = "RemoveDeviceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RemoveDevice", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveDevice")
    @ResponseWrapper(localName = "RemoveDeviceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveDeviceResponse")
    public Boolean removeDevice(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Long id,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        Long userId);

    /**
     * 
     * @param deviceId
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveCircuitDevice", action = "http://tempuri.org/IBPMWebInterface/RemoveCircuitDevice")
    @WebResult(name = "RemoveCircuitDeviceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RemoveCircuitDevice", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveCircuitDevice")
    @ResponseWrapper(localName = "RemoveCircuitDeviceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveCircuitDeviceResponse")
    public Boolean removeCircuitDevice(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
        Long deviceId);

    /**
     * 
     * @param batteryPackId
     * @param batteryId
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmdevices.BatteryThreshold
     */
    @WebMethod(operationName = "GetBatteryThreshold", action = "http://tempuri.org/IBPMWebInterface/GetBatteryThreshold")
    @WebResult(name = "GetBatteryThresholdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBatteryThreshold", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryThreshold")
    @ResponseWrapper(localName = "GetBatteryThresholdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryThresholdResponse")
    public BatteryThreshold getBatteryThreshold(
        @WebParam(name = "batteryPackId", targetNamespace = "http://tempuri.org/")
        Long batteryPackId,
        @WebParam(name = "batteryId", targetNamespace = "http://tempuri.org/")
        Long batteryId);

    /**
     * 
     * @param batteryPackId
     * @param batteryId
     * @param batteryThreshold
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateBatteryThreshold", action = "http://tempuri.org/IBPMWebInterface/UpdateBatteryThreshold")
    @WebResult(name = "UpdateBatteryThresholdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateBatteryThreshold", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateBatteryThreshold")
    @ResponseWrapper(localName = "UpdateBatteryThresholdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateBatteryThresholdResponse")
    public Boolean updateBatteryThreshold(
        @WebParam(name = "batteryPackId", targetNamespace = "http://tempuri.org/")
        Long batteryPackId,
        @WebParam(name = "batteryId", targetNamespace = "http://tempuri.org/")
        Long batteryId,
        @WebParam(name = "batteryThreshold", targetNamespace = "http://tempuri.org/")
        BatteryThreshold batteryThreshold);

    /**
     * 
     * @param batteryPackId
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmdevices.BatteryPackThreshold
     */
    @WebMethod(operationName = "GetBatteryGroupThreshold", action = "http://tempuri.org/IBPMWebInterface/GetBatteryGroupThreshold")
    @WebResult(name = "GetBatteryGroupThresholdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBatteryGroupThreshold", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryGroupThreshold")
    @ResponseWrapper(localName = "GetBatteryGroupThresholdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryGroupThresholdResponse")
    public BatteryPackThreshold getBatteryGroupThreshold(
        @WebParam(name = "batteryPackId", targetNamespace = "http://tempuri.org/")
        Long batteryPackId);

    /**
     * 
     * @param batteryPackId
     * @param batteryGroupThreshold
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateBatteryGroupThreshold", action = "http://tempuri.org/IBPMWebInterface/UpdateBatteryGroupThreshold")
    @WebResult(name = "UpdateBatteryGroupThresholdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateBatteryGroupThreshold", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateBatteryGroupThreshold")
    @ResponseWrapper(localName = "UpdateBatteryGroupThresholdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateBatteryGroupThresholdResponse")
    public Boolean updateBatteryGroupThreshold(
        @WebParam(name = "batteryPackId", targetNamespace = "http://tempuri.org/")
        Long batteryPackId,
        @WebParam(name = "batteryGroupThreshold", targetNamespace = "http://tempuri.org/")
        BatteryPackThreshold batteryGroupThreshold);

    /**
     * 
     * @param areaId
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmdevices_vendor.ArrayOfBatteryPack
     */
    @WebMethod(operationName = "GetBatteryPackByArea", action = "http://tempuri.org/IBPMWebInterface/GetBatteryPackByArea")
    @WebResult(name = "GetBatteryPackByAreaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBatteryPackByArea", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryPackByArea")
    @ResponseWrapper(localName = "GetBatteryPackByAreaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryPackByAreaResponse")
    public ArrayOfBatteryPack getBatteryPackByArea(
        @WebParam(name = "areaId", targetNamespace = "http://tempuri.org/")
        Long areaId);

    /**
     * 
     * @param pageIndex
     * @param pageDataCount
     * @param isIgnored
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmdevices_vendor.ArrayOfAlarm
     */
    @WebMethod(operationName = "GetRealTimeAlarm", action = "http://tempuri.org/IBPMWebInterface/GetRealTimeAlarm")
    @WebResult(name = "GetRealTimeAlarmResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRealTimeAlarm", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRealTimeAlarm")
    @ResponseWrapper(localName = "GetRealTimeAlarmResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRealTimeAlarmResponse")
    public ArrayOfAlarm getRealTimeAlarm(
        @WebParam(name = "isIgnored", targetNamespace = "http://tempuri.org/")
        Boolean isIgnored,
        @WebParam(name = "pageIndex", targetNamespace = "http://tempuri.org/")
        Integer pageIndex,
        @WebParam(name = "pageDataCount", targetNamespace = "http://tempuri.org/")
        Integer pageDataCount);

    /**
     * 
     * @param isIgnored
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "GetRealTimeAlarmCount", action = "http://tempuri.org/IBPMWebInterface/GetRealTimeAlarmCount")
    @WebResult(name = "GetRealTimeAlarmCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRealTimeAlarmCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRealTimeAlarmCount")
    @ResponseWrapper(localName = "GetRealTimeAlarmCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRealTimeAlarmCountResponse")
    public Long getRealTimeAlarmCount(
        @WebParam(name = "isIgnored", targetNamespace = "http://tempuri.org/")
        Boolean isIgnored);

    /**
     * 
     * @param alarmId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IgnoreAlarm", action = "http://tempuri.org/IBPMWebInterface/IgnoreAlarm")
    @WebResult(name = "IgnoreAlarmResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IgnoreAlarm", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IgnoreAlarm")
    @ResponseWrapper(localName = "IgnoreAlarmResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IgnoreAlarmResponse")
    public Boolean ignoreAlarm(
        @WebParam(name = "alarmId", targetNamespace = "http://tempuri.org/")
        Long alarmId);

    /**
     * 
     * @param alarmType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IgnoreAlarmType", action = "http://tempuri.org/IBPMWebInterface/IgnoreAlarmType")
    @WebResult(name = "IgnoreAlarmTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IgnoreAlarmType", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IgnoreAlarmType")
    @ResponseWrapper(localName = "IgnoreAlarmTypeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IgnoreAlarmTypeResponse")
    public Boolean ignoreAlarmType(
        @WebParam(name = "alarmType", targetNamespace = "http://tempuri.org/")
        AlarmAlarmType alarmType);

    /**
     * 
     * @param batteryPackAlarmDllByteBuff
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "LoadBatteryPackAlarmDll", action = "http://tempuri.org/IBPMWebInterface/LoadBatteryPackAlarmDll")
    @WebResult(name = "LoadBatteryPackAlarmDllResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoadBatteryPackAlarmDll", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoadBatteryPackAlarmDll")
    @ResponseWrapper(localName = "LoadBatteryPackAlarmDllResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoadBatteryPackAlarmDllResponse")
    public Boolean loadBatteryPackAlarmDll(
        @WebParam(name = "batteryPackAlarmDllByteBuff", targetNamespace = "http://tempuri.org/")
        byte[] batteryPackAlarmDllByteBuff);

    /**
     * 
     * @param batteryAlarmDllByteBuff
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "LoadBatteryAlarmDll", action = "http://tempuri.org/IBPMWebInterface/LoadBatteryAlarmDll")
    @WebResult(name = "LoadBatteryAlarmDllResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoadBatteryAlarmDll", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoadBatteryAlarmDll")
    @ResponseWrapper(localName = "LoadBatteryAlarmDllResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoadBatteryAlarmDllResponse")
    public Boolean loadBatteryAlarmDll(
        @WebParam(name = "batteryAlarmDllByteBuff", targetNamespace = "http://tempuri.org/")
        byte[] batteryAlarmDllByteBuff);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBatteryPackCalcAlarmDllVersion", action = "http://tempuri.org/IBPMWebInterface/GetBatteryPackCalcAlarmDllVersion")
    @WebResult(name = "GetBatteryPackCalcAlarmDllVersionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBatteryPackCalcAlarmDllVersion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryPackCalcAlarmDllVersion")
    @ResponseWrapper(localName = "GetBatteryPackCalcAlarmDllVersionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryPackCalcAlarmDllVersionResponse")
    public String getBatteryPackCalcAlarmDllVersion();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBatteryCalcAlarmDllVersion", action = "http://tempuri.org/IBPMWebInterface/GetBatteryCalcAlarmDllVersion")
    @WebResult(name = "GetBatteryCalcAlarmDllVersionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBatteryCalcAlarmDllVersion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryCalcAlarmDllVersion")
    @ResponseWrapper(localName = "GetBatteryCalcAlarmDllVersionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryCalcAlarmDllVersionResponse")
    public String getBatteryCalcAlarmDllVersion();

    /**
     * 
     * @param circuitId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetECUVersion", action = "http://tempuri.org/IBPMWebInterface/GetECUVersion")
    @WebResult(name = "GetECUVersionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetECUVersion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetECUVersion")
    @ResponseWrapper(localName = "GetECUVersionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetECUVersionResponse")
    public String getECUVersion(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId);

    /**
     * 
     * @param stageIndex
     * @param craftId
     * @param circuitId
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "StartFormation", action = "http://tempuri.org/IBPMWebInterface/StartFormation")
    @WebResult(name = "StartFormationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartFormation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartFormation")
    @ResponseWrapper(localName = "StartFormationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartFormationResponse")
    public Integer startFormation(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "craftId", targetNamespace = "http://tempuri.org/")
        Long craftId,
        @WebParam(name = "stageIndex", targetNamespace = "http://tempuri.org/")
        Integer stageIndex);

    /**
     * 
     * @param circuitId
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "PauseFormation", action = "http://tempuri.org/IBPMWebInterface/PauseFormation")
    @WebResult(name = "PauseFormationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PauseFormation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PauseFormation")
    @ResponseWrapper(localName = "PauseFormationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PauseFormationResponse")
    public Integer pauseFormation(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId);

    /**
     * 
     * @param circuitId
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "ResumeFormation", action = "http://tempuri.org/IBPMWebInterface/ResumeFormation")
    @WebResult(name = "ResumeFormationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ResumeFormation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResumeFormation")
    @ResponseWrapper(localName = "ResumeFormationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResumeFormationResponse")
    public Integer resumeFormation(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId);

    /**
     * 
     * @param circuitId
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "StopFormation", action = "http://tempuri.org/IBPMWebInterface/StopFormation")
    @WebResult(name = "StopFormationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StopFormation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StopFormation")
    @ResponseWrapper(localName = "StopFormationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StopFormationResponse")
    public Integer stopFormation(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId);

    /**
     * 
     * @param circuitId
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "JumpToNextStage", action = "http://tempuri.org/IBPMWebInterface/JumpToNextStage")
    @WebResult(name = "JumpToNextStageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "JumpToNextStage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JumpToNextStage")
    @ResponseWrapper(localName = "JumpToNextStageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JumpToNextStageResponse")
    public Integer jumpToNextStage(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId);

    /**
     * 
     * @param stageIndex
     * @param circuitId
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "JumpToStage", action = "http://tempuri.org/IBPMWebInterface/JumpToStage")
    @WebResult(name = "JumpToStageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "JumpToStage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JumpToStage")
    @ResponseWrapper(localName = "JumpToStageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JumpToStageResponse")
    public Integer jumpToStage(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "stageIndex", targetNamespace = "http://tempuri.org/")
        Integer stageIndex);

    /**
     * 
     * @param circuitId
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "ResetDCDC", action = "http://tempuri.org/IBPMWebInterface/ResetDCDC")
    @WebResult(name = "ResetDCDCResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ResetDCDC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResetDCDC")
    @ResponseWrapper(localName = "ResetDCDCResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResetDCDCResponse")
    public Integer resetDCDC(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId);

    /**
     * 
     * @param realVoltageIn150V
     * @param realVoltageIn30V
     * @param circuitId
     * @param realVoltageIn300V
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "CalibrationVoltage", action = "http://tempuri.org/IBPMWebInterface/CalibrationVoltage")
    @WebResult(name = "CalibrationVoltageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalibrationVoltage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalibrationVoltage")
    @ResponseWrapper(localName = "CalibrationVoltageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalibrationVoltageResponse")
    public Integer calibrationVoltage(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "realVoltageIn30V", targetNamespace = "http://tempuri.org/")
        Double realVoltageIn30V,
        @WebParam(name = "realVoltageIn150V", targetNamespace = "http://tempuri.org/")
        Double realVoltageIn150V,
        @WebParam(name = "realVoltageIn300V", targetNamespace = "http://tempuri.org/")
        Double realVoltageIn300V);

    /**
     * 
     * @param realCurrentIn50A
     * @param realCurrentIn10A
     * @param realCurrentIn100A
     * @param circuitId
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "CalibrationCurrent", action = "http://tempuri.org/IBPMWebInterface/CalibrationCurrent")
    @WebResult(name = "CalibrationCurrentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalibrationCurrent", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalibrationCurrent")
    @ResponseWrapper(localName = "CalibrationCurrentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalibrationCurrentResponse")
    public Integer calibrationCurrent(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "realCurrentIn10A", targetNamespace = "http://tempuri.org/")
        Double realCurrentIn10A,
        @WebParam(name = "realCurrentIn50A", targetNamespace = "http://tempuri.org/")
        Double realCurrentIn50A,
        @WebParam(name = "realCurrentIn100A", targetNamespace = "http://tempuri.org/")
        Double realCurrentIn100A);

    /**
     * 
     * @param circuitId
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "CalibrationTime", action = "http://tempuri.org/IBPMWebInterface/CalibrationTime")
    @WebResult(name = "CalibrationTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalibrationTime", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalibrationTime")
    @ResponseWrapper(localName = "CalibrationTimeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalibrationTimeResponse")
    public Integer calibrationTime(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId);

    /**
     * 
     * @param craftId
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "UpdateCraft", action = "http://tempuri.org/IBPMWebInterface/UpdateCraft")
    @WebResult(name = "UpdateCraftResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateCraft", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateCraft")
    @ResponseWrapper(localName = "UpdateCraftResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateCraftResponse")
    public Integer updateCraft(
        @WebParam(name = "craftId", targetNamespace = "http://tempuri.org/")
        Long craftId);

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfanyType
     */
    @WebMethod(operationName = "GetVoltageCalibrationInfoList", action = "http://tempuri.org/IBPMWebInterface/GetVoltageCalibrationInfoList")
    @WebResult(name = "GetVoltageCalibrationInfoListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVoltageCalibrationInfoList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVoltageCalibrationInfoList")
    @ResponseWrapper(localName = "GetVoltageCalibrationInfoListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVoltageCalibrationInfoListResponse")
    public ArrayOfanyType getVoltageCalibrationInfoList();

    /**
     * 
     * @param circuitId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBatteryPackAlarmCalcAssemblyObject", action = "http://tempuri.org/IBPMWebInterface/GetBatteryPackAlarmCalcAssemblyObject")
    @WebResult(name = "GetBatteryPackAlarmCalcAssemblyObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBatteryPackAlarmCalcAssemblyObject", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryPackAlarmCalcAssemblyObject")
    @ResponseWrapper(localName = "GetBatteryPackAlarmCalcAssemblyObjectResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryPackAlarmCalcAssemblyObjectResponse")
    public String getBatteryPackAlarmCalcAssemblyObject(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId);

    /**
     * 
     * @param index
     * @param circuitId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBatteryAlarmCalcAssemblyObject", action = "http://tempuri.org/IBPMWebInterface/GetBatteryAlarmCalcAssemblyObject")
    @WebResult(name = "GetBatteryAlarmCalcAssemblyObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBatteryAlarmCalcAssemblyObject", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryAlarmCalcAssemblyObject")
    @ResponseWrapper(localName = "GetBatteryAlarmCalcAssemblyObjectResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBatteryAlarmCalcAssemblyObjectResponse")
    public String getBatteryAlarmCalcAssemblyObject(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "index", targetNamespace = "http://tempuri.org/")
        Long index);

    /**
     * 
     * @param registerAddress
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "GetSfBCUConfig", action = "http://tempuri.org/IBPMWebInterface/GetSfBCUConfig")
    @WebResult(name = "GetSfBCUConfigResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSfBCUConfig", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSfBCUConfig")
    @ResponseWrapper(localName = "GetSfBCUConfigResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSfBCUConfigResponse")
    public Boolean getSfBCUConfig(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "registerAddress", targetNamespace = "http://tempuri.org/")
        Integer registerAddress);

    /**
     * 
     * @param bcu
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetSfBCUConfig", action = "http://tempuri.org/IBPMWebInterface/SetSfBCUConfig")
    @WebResult(name = "SetSfBCUConfigResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetSfBCUConfig", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetSfBCUConfig")
    @ResponseWrapper(localName = "SetSfBCUConfigResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetSfBCUConfigResponse")
    public Boolean setSfBCUConfig(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "bcu", targetNamespace = "http://tempuri.org/")
        SfBCU bcu);

    /**
     * 
     * @param oldRegisterAddress
     * @param bcu
     * @param newRegisterAddress
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateSfBCUConfig", action = "http://tempuri.org/IBPMWebInterface/UpdateSfBCUConfig")
    @WebResult(name = "UpdateSfBCUConfigResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateSfBCUConfig", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateSfBCUConfig")
    @ResponseWrapper(localName = "UpdateSfBCUConfigResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateSfBCUConfigResponse")
    public Boolean updateSfBCUConfig(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "bcu", targetNamespace = "http://tempuri.org/")
        SfBCU bcu,
        @WebParam(name = "newRegisterAddress", targetNamespace = "http://tempuri.org/")
        Integer newRegisterAddress,
        @WebParam(name = "oldRegisterAddress", targetNamespace = "http://tempuri.org/")
        Integer oldRegisterAddress);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmdevices_vendor.SfBCU
     */
    @WebMethod(operationName = "GetSfBCUConfigData", action = "http://tempuri.org/IBPMWebInterface/GetSfBCUConfigData")
    @WebResult(name = "GetSfBCUConfigDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSfBCUConfigData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSfBCUConfigData")
    @ResponseWrapper(localName = "GetSfBCUConfigDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSfBCUConfigDataResponse")
    public SfBCU getSfBCUConfigData();

    /**
     * 
     * @param ecu
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetSfECUConfig", action = "http://tempuri.org/IBPMWebInterface/SetSfECUConfig")
    @WebResult(name = "SetSfECUConfigResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetSfECUConfig", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetSfECUConfig")
    @ResponseWrapper(localName = "SetSfECUConfigResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetSfECUConfigResponse")
    public Boolean setSfECUConfig(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "ecu", targetNamespace = "http://tempuri.org/")
        SfECU ecu);

    /**
     * 
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "GetSfECUConfig", action = "http://tempuri.org/IBPMWebInterface/GetSfECUConfig")
    @WebResult(name = "GetSfECUConfigResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSfECUConfig", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSfECUConfig")
    @ResponseWrapper(localName = "GetSfECUConfigResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSfECUConfigResponse")
    public Boolean getSfECUConfig(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmdevices_vendor.SfECU
     */
    @WebMethod(operationName = "GetSfECUConfigData", action = "http://tempuri.org/IBPMWebInterface/GetSfECUConfigData")
    @WebResult(name = "GetSfECUConfigDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSfECUConfigData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSfECUConfigData")
    @ResponseWrapper(localName = "GetSfECUConfigDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSfECUConfigDataResponse")
    public SfECU getSfECUConfigData();

    /**
     * 
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "CheckResistance", action = "http://tempuri.org/IBPMWebInterface/CheckResistance")
    @WebResult(name = "CheckResistanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckResistance", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckResistance")
    @ResponseWrapper(localName = "CheckResistanceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckResistanceResponse")
    public Boolean checkResistance(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId);

    /**
     * 
     * @param dischargeInputCurrent
     * @param dischargeOutputVoltage
     * @param chargeInputCurrent
     * @param chargeOutputVoltage
     * @param circuitId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetCurrentDucer", action = "http://tempuri.org/IBPMWebInterface/SetCurrentDucer")
    @WebResult(name = "SetCurrentDucerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetCurrentDucer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetCurrentDucer")
    @ResponseWrapper(localName = "SetCurrentDucerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetCurrentDucerResponse")
    public Boolean setCurrentDucer(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId,
        @WebParam(name = "chargeInputCurrent", targetNamespace = "http://tempuri.org/")
        Double chargeInputCurrent,
        @WebParam(name = "chargeOutputVoltage", targetNamespace = "http://tempuri.org/")
        Double chargeOutputVoltage,
        @WebParam(name = "dischargeInputCurrent", targetNamespace = "http://tempuri.org/")
        Double dischargeInputCurrent,
        @WebParam(name = "dischargeOutputVoltage", targetNamespace = "http://tempuri.org/")
        Double dischargeOutputVoltage);

    /**
     * 
     * @param circuitId
     * @return
     *     returns org.datacontract.schemas._2004._07.bpmservice.CurentDucer
     */
    @WebMethod(operationName = "GetCurrentDucer", action = "http://tempuri.org/IBPMWebInterface/GetCurrentDucer")
    @WebResult(name = "GetCurrentDucerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCurrentDucer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrentDucer")
    @ResponseWrapper(localName = "GetCurrentDucerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrentDucerResponse")
    public CurentDucer getCurrentDucer(
        @WebParam(name = "circuitId", targetNamespace = "http://tempuri.org/")
        Long circuitId);

}
